### ISSUE TITLE
Address feedback sent in

### ISSUE THREAD

**Issue by acorncom** [glimmerjs/glimmer-website#27]
There was a good and thoughtful issue opened at https://github.com/glimmerjs/glimmer-component/issues/29 that has some good suggestions we should address:

- [x] UI components for what? Visitors should get this clear immediately
- [ ] "Attention to detail of ember" - is that a quality comparison, or is it only for ember framework?
- [ ] UI projects should have at least one or two screenshots
Should mention at least one actual feature or component
- [x] GitHub link doesn't go to a repo. Instead it's a list of repos that you have to click around in to find the main project.
- [ ] API docs link goes to a page that is blank except for another link to the actual API docs. If docs are not ready better to just link to "#", avoid frustration

**Comment by tomdale** [comment]
This is great feedback! I agree with many of these points. I think there is maybe a little bit of confusion embedded in this feedback (which is itself helpful!). It sounds like we're coming across as a _library of UI components_ instead of a _library for building your *own* UI components_, i.e., Bootstrap instead of React.

Other things we should prioritize is:

1. A "hero" code sample (suggested by @bterlson). This is a little tricky because of how important file paths are for the resolver. How do we communicate the file system hierarchy succinctly?
2. Some kind of playground for people to try out components.

**Comment by acorncom** [comment]
Re: "hero" code sample, @locks and I had been discussing reworking the guides to implement the weather widget shown in the video.  We could also have a few simple widgets on the homepage ...

**Comment by locks** [comment]
Pinging @whitneyland as they were the originators of the feedback!

**Comment by max** [comment]
The [initial mockup included a code sample](https://github.com/tomdale/glimmer-website/issues/1). It also shows the paths (I can make it clearer with a faux file browser to the left).

**Comment by bterlson** [comment]
@max fwiw I like the "tabs" showing the path of the file 👍. File browser might be too much. If you make sure that the most illustrative sample is on the tab that shows by default you might be fine. $0.02; not a designer.

**Comment by whitneyland** [comment]
thanks all for being receptive, it takes a stronger person to not get defensive.

**Comment by wycats** [comment]
@tomdale we had discussed using some of the ideas in your original mockup (especially above-the-fold code). Are you working on that?
